---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Download and install Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: Unzip Terraform
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin"
        remote_src: yes

    - name: Set permissions for Terraform
      file:
        path: "/usr/local/bin/terraform"
        mode: "0755"